@echo off
echo 🕸️ Starting Visualizer Studio Pro (PC Edition)...
echo --------------------------------------------------
echo [1/2] Launching Background Server...
start /b npm run dev
echo [2/2] Waiting for server to warm up...
timeout /t 5 > nul
echo 🚀 Opening Desktop Window...
npm run electron
pause
